on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts

      - name: Build and test with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Deploy to production
        if: success()
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
        run: |
          /usr/bin/rsync -avz --exclude='target/' --exclude='.git/' ./ kmaganyane83@${{ secrets.PRODUCTION_SERVER }}:/opt/myapp/





