on:
  push:
    branches: [ trunk ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: ssh -v -o "StrictHostKeyChecking=no" kmaganyane83@${{ secrets.PRODUCTION_SERVER }} "echo connected"

      - name: Build and test with Maven
        run: mvn clean package

      - name: Deploy to production
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
        run: |
          ssh -o "StrictHostKeyChecking=no" kmaganyane83@$PRODUCTION_SERVER "mkdir -p /opt/myapp"
          rsync -avz --exclude='target/' --exclude='.git/' ./ kmaganyane83@$PRODUCTION_SERVER:/opt/myapp/


