on:
  push:
    branches: [ trunk ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build and test with Maven
        run: mvn clean package
      - name: Deploy to production
        env:
          PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
        run: |
          ssh -o "StrictHostKeyChecking=no" $PRODUCTION_SERVER "mkdir -p /opt/myapp"
          mvn deploy -Ddeploy.server=$PRODUCTION_SERVER -Ddeploy.path=/opt/myapp

  
